.. trendpy documentation master file


trendpy
********

.. toctree::
   :maxdepth: 1

trendpy is a bayesian filtering micro library.

The library also supports bayesian regression models (Lasso and Ridge).

Models are fitted using MCMC algorithms.

Requirements
============

trenpy is build on top of the following libraries:

.. Numpy (http://www.numpy.org) 
.. SciPy (http://www.scipy.org)
.. Pandas (http://pandas.pydata.org/)
.. matplotlib (http://http://matplotlib.org/)
.. statsmodels (http://www.statsmodels.org/stable/index.html)

and for testing I chose py.test (http://pytest.org/latest/)

Issues
------

Should you encounter any issue with the library ou can raise them here: https://github.com/ronsenbergVI/filterpy/issues

.. include:: contents.rst.inc
