User's Guide
------------

This part of the documentation focuses on step-by-step
instructions for trend and volatility filtering with trendpy.

.. toctree::
   :maxdepth: 2

   introduction
   installation
   tutorial

API Reference
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api

Additional Notes
----------------

Additional notes for anyone interested.

.. toctree::
   :maxdepth: 2

   changes
   license
   contributing

Indices and tables
----------------

.. toctree::
   :maxdepth: 2

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`
